export { default as AnalyticsIcon } from "./analytics.svg?react";
export { default as DeFlag } from "./deFlag.svg?react";
export { default as EnFlag } from "./enFlag.svg?react";
export { default as LogoIcon } from "./logo.svg?react";
export { default as LogoIconSmall } from "./logoSmall.svg?react";
export { default as NoExistIcon } from "./noExist.svg?react";
export { default as NotFound } from "./notFound.svg?react";
export { default as RuFlag } from "./ruFlag.svg?react";
export { default as SpinnerIcon } from "./spinner.svg?react";
